sudo: true
language: cpp
matrix:
  include:
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gcc-8
          - g++-8
script:
  - export CXX=g++-8
  - export CC=gcc-8
  - sudo add-apt-repository ppa:beineri/opt-qt-5.10.1-trusty -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq qt510base qt510multimedia qt510translations qt510tools qt5103d qt510canvas3d qt510quickcontrols qt510quickcontrols2 qt510datavis3d-no-lgpl
  - sudo apt search qt510
  - source /opt/qt510/bin/qt510-env.sh 
  - export QTHOME=/opt/qt510
  - qmake ShieldingModule2.pro
  - ls /opt/qt510/
  - ls /opt/qt510/bin
  - make -j20

